/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata.base

data class Stock(val value: Int) {
    companion object{
        val NEUTRAL_ADDITION = Stock(0)
        val NEUTRAL_MULTIPLY = Stock(1)
    }

    fun combine(stock: Stock): Stock {
        return Stock(stock.value + value)
    }

    fun multiply(stock: Stock) = Stock(stock.value * value)
}




